apiVersion: v1
kind: Service
metadata:
    name: nginx
    labels:
        app: app
spec:
    ports:
        - name: http
          port: 80
          targetPort: 80
    selector:
        app: app
    type: LoadBalancer
